### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by rogersm** [mudcoders/guildmud#11]
Now that we have Travis CI integration, we need a test suit. I propose to use [Check](https://libcheck.github.io/check/).

It's small, easy to use, and [documented](https://libcheck.github.io/check/doc/check_html/index.html).

Are we ok to move to Check or do you prefer something different?

**Comment by zachflower** [comment]
It looks like it can be installed on [basically any system](https://libcheck.github.io/check/web/install.html), so I'm down with it. How does it compare with CUnit?

**Comment by rogersm** [comment]
Check has some additional functionality, like fixtures, but both have a lot in common. Happy to use CUnit if the team is more confortable with CUnit.

By the way, Check (and CUnit) are LPGL... this should not clash with guildmud MIT license, but are we ok to use LGPL?

**Comment by zachflower** [comment]
As far as I know LGPL doesn't conflict with our MIT license, but if anyone has a more informed opinion than mine I welcome it.

**Comment by rogersm** [comment]
No, it does not conflict with MIT license.

One final question before submitting the PR, is check available in Vagrant? or is there anything easier to deploy?
