### ISSUE TITLE
Add SQLite for data storage

### ISSUE THREAD

**Issue by robotastronaut-zz** [mudcoders/guildmud#3]
We are leaning towards using SQLite as our data storage solution. How we go about tying it into the other systems hasn't been discussed. The first steps would likely involve refactoring the existing data storage capabilities of SocketMUD to leverage SQLite. Should there be an option to duplicate data to flat files as well?

**Comment by Trevoke** [comment]
Sqlite is single-write isn't it? Will that lead to concurrency issues /
bottlenecks?

**Comment by xenith** [comment]
It's a question of whether you run off of everything in-memory and only use SQLite for persistence. (Many classic MUDs I'm aware of operate that way with flat files.)

**Comment by Trevoke** [comment]
Ah, gotcha. Right.

**Comment by zachflower** [comment]
Yeah, that's the Diku convention. Keeping everything in-memory is significantly faster (although in the current era of SSDs the benefits might not be as drastic as they once were).

**Comment by xenith** [comment]
Regarding duplicating, I don't think that's necessary. Just set up an administrative CLI (in game or out) to edit the data so you don't have to write raw SQL. And for backups, well, you can just copy the .sqlite file on a regular basis.
